module.exports = {
  mapNames: function(){
    return [
      "albania",
      "andorra",
      "armenia",
      "austria",
      "bangladesh",
      "barbados",
      "belarus",
      "belgium",
      "belize",
      "benin",
      "bolivia",
      "botswana",
      "cameroon",
      "costa rica",
      "cyprus",
      "djibouti",
      "dominica",
      "eritrea",
      "ethiopia",
      "gabon",
      "georgia",
      "guyana",
      "iceland",
      "jamaica",
      "jordan",
      "kenya",
      "kyrgyzstan",
      "lebanon",
      "lithuania",
      "namibia",
      "niger",
      "oman",
      "rwanda",
      "singapore",
      "slovakia",
      "south africa",
      "south korea",
      "syria",
      "togo",
      "turkmenistan"
    ]
  }
}
